#!/bin/bash
version=`python3 -c "import electrum-vestx; print(electrum-vestx.version.ELECTRUM_VERSION)"`
sig=`./run_electrum-vestx -w $SIGNING_WALLET signmessage $SIGNING_ADDRESS $version`
echo "{ \"version\":\"$version\", \"signatures\":{ \"$SIGNING_ADDRESS\":\"$sig\"}}"
