sudo: required
language: python
services:
- docker
addons:
  apt:
    sources:
      - sourceline: 'ppa:tah83/secp256k1'
    packages:
      - libusb-1.0-0-dev
      - libudev-dev
      - libsecp256k1-0
matrix:
  include:
  - if: tag =~ .+
    os: osx
    language: ruby
    osx_image: xcode8
  - os: linux
    python: "3.6"
    dist: xenial
  - os: linux
    python: "3.7"
    dist: xenial
before_install:
- source contrib/vestx/travis/electrum_vestx_version_env.sh
- echo electrum-vestx version is $VESTX_ELECTRUM_VERSION
- mkdir -p build && cp contrib/vestx/travis/* ./build/
- if [[ -n $TRAVIS_TAG ]] && [[ $TRAVIS_OS_NAME == 'osx' ]]; then
      ./build/before_install-osx.sh;
  fi
- if [[ -n $TRAVIS_TAG ]] && [[ $TRAVIS_OS_NAME == 'linux' ]] && [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then
      ./build/before_install-linux.sh;
  fi
- if [[ -n $TRAVIS_TAG ]] && [[ $TRAVIS_OS_NAME == 'linux' ]] && [[ $TRAVIS_PYTHON_VERSION == '3.7' ]]; then
      ./build/before_install-linux-apk.sh;
  fi
install:
- if [[ -z $TRAVIS_TAG ]] && [[ $TRAVIS_OS_NAME == 'linux' ]]; then
      pip install tox; pip install tox-travis;
  fi
script:
- if [[ -z $TRAVIS_TAG ]] && [[ $TRAVIS_OS_NAME == 'linux' ]];then
      tox;
  fi
- if [[ -n $TRAVIS_TAG ]] && [[ $TRAVIS_OS_NAME == 'osx' ]]; then
      ./build/travis-build-osx.sh ;
  fi
- if [[ -n $TRAVIS_TAG ]] && [[ $TRAVIS_OS_NAME == 'linux' ]] && [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then
      ./build/travis-build-linux.sh;
  fi
- if [[ -n $TRAVIS_TAG ]] && [[ $TRAVIS_OS_NAME == 'linux' ]] && [[ $TRAVIS_PYTHON_VERSION == '3.7' ]]; then
      ./build/travis-build-linux-apk.sh;
  fi
deploy:
- provider: releases
  api_key:
    secure: sbjZ+oSSzNGk1g4xQq4qTlMVTznIqxQn9lVZNpbACeRTO22aXEABlcu3Ko82RhUrYyV7UBZbWyBnGEhF5C7PE7FAsFptEaTYi+F/2ZENAwEaLCkfXv1MBmKKGPryLgRoWL6+HNPZlycjMzucq8pUt2S7WysdHSpaC7fvaG8HuqnnC2/+JArSmkXv0JzNtbFZEkeIAzj5y3HL/THfSUPDfE2KtVfx/524/wM/dXZrS3kkF3BANdnCOpY1XNZyKmrS8i5sYbu5bFRWvoOP38DQ1sKguwQG+EIpGtFrJJKmFBvMcLMmvGePtmzOOgA+dp3hQwpyBGPmAf7An11nP1D/Io060Gi3IOlwf3yTaiwje09ikSdwXrYGpxjjp6yo14qywgtSKL7Uk1Pkx0UcumPBJ+1O+wzYykS1+fgrTpqiw87tjhw89GIlXfewug3tH2lG8I6GgGsWaxQODGBK72oKkhUH1Rj4ctrKjm8GxI9xJ1fM6fLc1uma33kiEQJAhy9qja23yJ860aDqV5VPwEvSYfKcI92MRGg+VBLnGs32p5gzvZKDOCDfqe0p5az1BhUE+Jbh2CtyJdOstaOZV67QqZxQOZpcd+e5R6PMoo4+wMp3NZSsTt4rDkmOGmMRrqrASUpz4vErqkLPZwvJmFKxVo9L9hpLjEE4ttcEm0a+OTM=
  file:
  - build/electrum-vestx/dist/Vestx-Electrum-$VESTX_ELECTRUM_VERSION-macosx.dmg
  on:
    repo: anonymouszar/electrum-vestx
    tags: true
    condition: "$TRAVIS_OS_NAME = osx"
- provider: releases
  api_key:
    secure: sbjZ+oSSzNGk1g4xQq4qTlMVTznIqxQn9lVZNpbACeRTO22aXEABlcu3Ko82RhUrYyV7UBZbWyBnGEhF5C7PE7FAsFptEaTYi+F/2ZENAwEaLCkfXv1MBmKKGPryLgRoWL6+HNPZlycjMzucq8pUt2S7WysdHSpaC7fvaG8HuqnnC2/+JArSmkXv0JzNtbFZEkeIAzj5y3HL/THfSUPDfE2KtVfx/524/wM/dXZrS3kkF3BANdnCOpY1XNZyKmrS8i5sYbu5bFRWvoOP38DQ1sKguwQG+EIpGtFrJJKmFBvMcLMmvGePtmzOOgA+dp3hQwpyBGPmAf7An11nP1D/Io060Gi3IOlwf3yTaiwje09ikSdwXrYGpxjjp6yo14qywgtSKL7Uk1Pkx0UcumPBJ+1O+wzYykS1+fgrTpqiw87tjhw89GIlXfewug3tH2lG8I6GgGsWaxQODGBK72oKkhUH1Rj4ctrKjm8GxI9xJ1fM6fLc1uma33kiEQJAhy9qja23yJ860aDqV5VPwEvSYfKcI92MRGg+VBLnGs32p5gzvZKDOCDfqe0p5az1BhUE+Jbh2CtyJdOstaOZV67QqZxQOZpcd+e5R6PMoo4+wMp3NZSsTt4rDkmOGmMRrqrASUpz4vErqkLPZwvJmFKxVo9L9hpLjEE4ttcEm0a+OTM=
  file:
  - build/electrum-vestx/dist/Vestx-Electrum-$VESTX_ELECTRUM_VERSION.tar.gz
  - build/electrum-vestx/dist/Vestx-Electrum-$VESTX_ELECTRUM_VERSION.zip
  - build/electrum-vestx/dist/Vestx-Electrum-$VESTX_ELECTRUM_VERSION-x86_64.AppImage
  - build/electrum-vestx/dist/Vestx-Electrum-$VESTX_ELECTRUM_VERSION-setup-win32.exe
  - build/electrum-vestx/dist/Vestx-Electrum-$VESTX_ELECTRUM_VERSION-setup-win64.exe
  - build/electrum-vestx/bin/Electrum_VESTX-$VESTX_ELECTRUM_APK_VERSION-release-unsigned.apk
  on:
    repo: anonymouszar/electrum-vestx
    tags: true
    condition: "$TRAVIS_OS_NAME = linux"
