#!/bin/bash

VERSION_STRING=(`grep ELECTRUM_VERSION electrum_vestx/version.py`)
VESTX_ELECTRUM_VERSION=${VERSION_STRING[2]}
VESTX_ELECTRUM_VERSION=${VESTX_ELECTRUM_VERSION#\'}
VESTX_ELECTRUM_VERSION=${VESTX_ELECTRUM_VERSION%\'}
export VESTX_ELECTRUM_VERSION

APK_VERSION_STRING=(`grep APK_VERSION electrum_vestx/version.py`)
VESTX_ELECTRUM_APK_VERSION=${APK_VERSION_STRING[2]}
VESTX_ELECTRUM_APK_VERSION=${VESTX_ELECTRUM_APK_VERSION#\'}
VESTX_ELECTRUM_APK_VERSION=${VESTX_ELECTRUM_APK_VERSION%\'}
export VESTX_ELECTRUM_APK_VERSION
